# Generated by Django 4.2 on 2025-05-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('imagen', models.ImageField(upload_to='portafolio/')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
